### ISSUE TITLE
Jota Session 9 - 2022-11-18 @Treyvaux

### ISSUE THREAD

**Issue by jorinho** [jota-one/jota.one#15]
# Ordre du jour

- [x] 2.0 - **Urban-Training**: Check de l'avancement du projet, expected:
  - [x] Démo du cluster
  - [x] Demo du figma website
- [x] Intégration Drosse 3 dans un projet (kupo en l'occurrence)
- [x] 4.0 - **Cat** Atelier apprivoisement de Manette par Annette (slot dédié à cette dernière)

**Comment by tadaii** [comment]
Résumé
- Tous les points abordés ont été finalisés sauf
- Integration Drosse 3 en cours sur kupo (sera fini dans le cadre du projet kupo)
